# Deployment for Spring Boot Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      name: springapppod
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: mylandmarktech/spring-boot-mongo
        ports:
        - containerPort: 8080  
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo
        - name: MONGO_INITDB_ROOT_USERNAME
          value: springapp
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodb@123
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
# MongoDB Replication Controller with host path Volume
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  clusterIP: None # Headless Service
  selector:
    app: mongod
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  selector:
    matchLabels:
      app: mongod
  serviceName: mongosvc
  replicas: 3
  template:
    metadata:
      labels:
        app: mongod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodbcontainer
        image: mongo
        command:
         - "mongod"
         - "--bind_ip"
         - "0.0.0.0"
         - "--replSet"
         - "MainRepSet"
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 27017
	env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: springapp 
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodb@123 
        volumeMounts:
        - name: mongodb-persistent-storage-claim
          mountPath: "/data/db"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
