version: '3'

services:
  jendarey-voting-app:
    image: g-research 
    container_name: jendarey-voting-app
    restart: always
    ports:
      - "14000:8080"
    networks:
      - jendarey-network
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: admin123
      MONGO_DB_HOSTNAME: jendarey-mongo

  jendarey-mongo:
    image: mongo
    container_name: jendarey-mongo
    restart: always
    networks:
      - jendarey-network
    environment:
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - jendarey-mongo-data-two:/data/db

networks:
  jendarey-network:
    driver: bridge

volumes:
  jendarey-mongo-data-two:


